-- =====================================================================
-- V1__init.sql  —  SecureTransfer initial schema (Phase 0)
--
-- Flyway runs this file automatically on application startup. The "V1"
-- prefix means "version 1"; later changes go in V2__*, V3__*, … and run
-- in order, once each. NEVER edit a migration after it has been applied
-- in a shared environment — add a new migration instead.
--
-- Conventions (see CLAUDE.md / the build plan):
--   * Money is NUMERIC(19,4) — exact decimal, never floating point.
--   * Timestamps are TIMESTAMPTZ (UTC instants), defaulting to now().
--   * IDs use GENERATED BY DEFAULT AS IDENTITY: auto-incrementing, but an
--     explicit value may still be supplied (handy for tests / seed data).
--   * "Enum-like" columns are VARCHAR guarded by CHECK constraints instead
--     of native ENUM types: simpler to map in JPA and easier to extend.
--   * ledger_entries and audit_log are APPEND-ONLY by policy — the app
--     only ever INSERTs them; nothing updates or deletes their rows.
--
-- Tables are created in dependency order so every FOREIGN KEY points at a
-- table that already exists.
-- =====================================================================


-- ---------------------------------------------------------------------
-- accounts — one row per bank account. The balance is kept correct
-- inside the transfer transaction (Phase 2). "version" backs JPA's
-- @Version optimistic-locking counter (Phase 2).
-- ---------------------------------------------------------------------
CREATE TABLE accounts (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT        NOT NULL,                  -- owner; the customers table arrives in Phase 1
    currency    CHAR(3)       NOT NULL,                  -- ISO 4217 code, e.g. 'USD'
    balance     NUMERIC(19,4) NOT NULL DEFAULT 0,
    version     BIGINT        NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- A bank account in this system can never go negative (no overdraft).
    -- This CHECK is a last line of defence even if app logic has a bug.
    CONSTRAINT accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT accounts_currency_format      CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX idx_accounts_customer_id ON accounts (customer_id);


-- ---------------------------------------------------------------------
-- idempotency_keys — remembers each POST /transfers request so a repeat
-- with the same key replays the stored result instead of running twice
-- (Phase 3). "key" is the PRIMARY KEY, giving us the UNIQUE guarantee the
-- duplicate-detection logic depends on.
-- ---------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    key               VARCHAR(255) PRIMARY KEY,
    request_hash      VARCHAR(64)  NOT NULL,             -- SHA-256 (hex) of the request body
    response_snapshot JSONB,                             -- the stored response to replay
    status            VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT idempotency_status_valid CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);


-- ---------------------------------------------------------------------
-- transfers — one row per money-movement attempt. References the two
-- accounts involved and (once Phase 3 wires it up) the idempotency key
-- that produced it.
-- ---------------------------------------------------------------------
CREATE TABLE transfers (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255),                        -- nullable until Phase 3
    from_account    BIGINT        NOT NULL,
    to_account      BIGINT        NOT NULL,
    amount          NUMERIC(19,4) NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT transfers_from_fk            FOREIGN KEY (from_account)    REFERENCES accounts (id),
    CONSTRAINT transfers_to_fk              FOREIGN KEY (to_account)      REFERENCES accounts (id),
    CONSTRAINT transfers_idempotency_fk     FOREIGN KEY (idempotency_key) REFERENCES idempotency_keys (key),
    -- One idempotency key maps to at most one transfer. Postgres allows many
    -- NULLs in a UNIQUE column, so pre-Phase-3 transfers (NULL key) are fine.
    CONSTRAINT transfers_idempotency_unique UNIQUE (idempotency_key),
    CONSTRAINT transfers_amount_positive    CHECK (amount > 0),
    CONSTRAINT transfers_distinct_accounts  CHECK (from_account <> to_account),
    CONSTRAINT transfers_status_valid       CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'FLAGGED'))
);

CREATE INDEX idx_transfers_from_account ON transfers (from_account);
CREATE INDEX idx_transfers_to_account   ON transfers (to_account);


-- ---------------------------------------------------------------------
-- ledger_entries — the append-only, double-entry ledger. Every transfer
-- writes TWO rows: a DEBIT on the sender and a CREDIT on the receiver,
-- equal in amount, so the pair nets to zero (Phase 2). Rows are inserted,
-- never updated or deleted — this is the immutable history of money.
-- ---------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT        NOT NULL,
    account_id  BIGINT        NOT NULL,
    direction   VARCHAR(6)    NOT NULL,                  -- 'DEBIT' (out) or 'CREDIT' (in)
    amount      NUMERIC(19,4) NOT NULL,                  -- always positive; direction carries the sign
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ledger_transfer_fk     FOREIGN KEY (transfer_id) REFERENCES transfers (id),
    CONSTRAINT ledger_account_fk      FOREIGN KEY (account_id)  REFERENCES accounts (id),
    CONSTRAINT ledger_direction_valid CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ledger_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_ledger_account_id  ON ledger_entries (account_id);   -- balance reconstruction & history
CREATE INDEX idx_ledger_transfer_id ON ledger_entries (transfer_id);  -- fetch both legs of a transfer


-- ---------------------------------------------------------------------
-- audit_log — append-only record of SENSITIVE actions: who did what, to
-- what, when (Phase 5). Separate from the ledger: the ledger tracks money
-- movements, this tracks accountability (freezes, viewing others' data,
-- manual fraud overrides). Insert-only.
-- ---------------------------------------------------------------------
CREATE TABLE audit_log (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor     VARCHAR(255) NOT NULL,             -- who acted (taken from the authenticated user)
    action    VARCHAR(100) NOT NULL,             -- what they did, e.g. 'ACCOUNT_FROZEN'
    target    VARCHAR(255),                      -- what was acted on, e.g. 'account:44'
    metadata  JSONB,                             -- optional extra context
    timestamp TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_actor     ON audit_log (actor);
CREATE INDEX idx_audit_action    ON audit_log (action);
CREATE INDEX idx_audit_timestamp ON audit_log (timestamp);


-- ---------------------------------------------------------------------
-- fraud_reviews — the AI fraud-triage agent's assessment of a flagged
-- transfer, plus the human's final call (Phase 6). The agent only
-- RECOMMENDS (decided_by = 'AGENT'); the human decision is recorded too
-- (decided_by = 'HUMAN'). Everything is kept for auditability.
-- ---------------------------------------------------------------------
CREATE TABLE fraud_reviews (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id        BIGINT       NOT NULL,
    risk_score         INTEGER,                  -- 0–100
    verdict            VARCHAR(50),
    reasoning          TEXT,
    recommended_action VARCHAR(20),              -- APPROVE / HOLD / ESCALATE
    decided_by         VARCHAR(20)  NOT NULL DEFAULT 'AGENT',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fraud_transfer_fk              FOREIGN KEY (transfer_id) REFERENCES transfers (id),
    CONSTRAINT fraud_risk_score_range         CHECK (risk_score IS NULL OR risk_score BETWEEN 0 AND 100),
    CONSTRAINT fraud_recommended_action_valid CHECK (recommended_action IS NULL OR recommended_action IN ('APPROVE', 'HOLD', 'ESCALATE')),
    CONSTRAINT fraud_decided_by_valid         CHECK (decided_by IN ('AGENT', 'HUMAN'))
);

CREATE INDEX idx_fraud_transfer_id ON fraud_reviews (transfer_id);
