-- =====================================================================
-- V2__customers_and_account_constraints.sql  —  Phase 1
--
-- Phase 0's V1 created `accounts` with a bare `customer_id` column, but no
-- `customers` table existed yet to point at. Phase 1 introduces customers,
-- links accounts to them, and makes one small type tweak to `currency`.
--
-- Flyway applies this automatically on top of V1, in order, exactly once.
-- =====================================================================

-- 1) The customers table: one row per customer (an account owner).
CREATE TABLE customers (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT customers_email_unique UNIQUE (email)
);

-- 2) Now that customers exists, enforce that every account points at a real
--    customer. Safe to add now because `accounts` still holds no rows.
ALTER TABLE accounts
    ADD CONSTRAINT accounts_customer_fk
    FOREIGN KEY (customer_id) REFERENCES customers (id);

-- 3) Use VARCHAR(3) instead of V1's CHAR(3) for the currency code: VARCHAR
--    avoids fixed-width space padding and maps cleanly to a Java String
--    (CHAR would otherwise mismatch JPA's String mapping). The "3 uppercase
--    letters" CHECK constraint from V1 still applies unchanged.
ALTER TABLE accounts
    ALTER COLUMN currency TYPE VARCHAR(3);
