-- =====================================================================
-- V3__users.sql  —  Authentication & authorization (Phase 4)
--
-- Adds the `users` table for login accounts. A user has a role (CUSTOMER,
-- TELLER, ADMIN). A CUSTOMER user is linked to their customer profile via
-- customer_id so we can enforce "a customer may only touch their OWN accounts";
-- staff users (TELLER/ADMIN) have no customer_id.
-- =====================================================================

CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) NOT NULL,
    password    VARCHAR(100) NOT NULL,   -- BCrypt hash (never plain text)
    role        VARCHAR(20)  NOT NULL,
    customer_id BIGINT,                  -- links a CUSTOMER user to its customer (null for staff)
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_role_valid      CHECK (role IN ('CUSTOMER', 'TELLER', 'ADMIN')),
    CONSTRAINT users_customer_fk     FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_users_customer_id ON users (customer_id);
